### ISSUE TITLE
Updating Features and Solvers

### ISSUE THREAD

**Issue by alonsovela96** [iamaya2/MatHH#42]
if I initialize a HH with certain number of features or solvers, the available features of solvers do not updates. 

<img width="477" alt="Captura de Pantalla 2022-03-25 a la(s) 10 14 16" src="https://user-images.githubusercontent.com/58858077/160159457-6ff64316-332f-420d-a09c-3fd001372013.png">
<img width="480" alt="Captura de Pantalla 2022-03-25 a la(s) 10 14 30" src="https://user-images.githubusercontent.com/58858077/160159458-b3c614e2-8f88-4bde-8a54-1d117ea24eae.png">

**Comment by iamaya2** [comment]
Checked the code and it is intended behavior. The idea is to first use the *assignFeatures* and *assignSolvers* methods to fix the IDs that will be used (numbers are auto-updated as well). Then, you shall use *initializeModel* to generate a random solution. Will update this method to only use nbRules, to avoid confusions.
